import type { Config } from "tailwindcss";

// export const colorScheme = {
//   name: "coolnight",
//   black: "#0B3B61",
//   red: "#FF3A3A",
//   green: "#52FFD0",
//   yellow: "#FFF383",
//   blue: "#1376F9",
//   purple: "#C792EA",
//   cyan: "#FF5ED4",
//   white: "#16FDA2",
//   brightBlack: "#63686D",
//   brightRed: "#FF54B0",
//   brightGreen: "#74FFD8",
//   brightYellow: "#FCF5AE",
//   brightBlue: "#388EFF",
//   brightPurple: "#AE81FF",
//   brightCyan: "#FF6AD7",
//   brightWhite: "#60FBBF",
//   background: "#010C18",
//   foreground: "#ECDEF4",
//   selectionBackground: "#38FF9C",
//   cursorColor: "#38FF9D",
// };
// export const colorScheme = {
//   name: "Guezwhoz",
//   black: "#080808",
//   red: "#ff5f5f",
//   green: "#87d7af",
//   yellow: "#d7d787",
//   blue: "#5fafd7",
//   purple: "#afafff",
//   cyan: "#5fd7d7",
//   white: "#dadada",
//   brightBlack: "#8a8a8a",
//   brightRed: "#d75f5f",
//   brightGreen: "#afd7af",
//   brightYellow: "#d7d7af",
//   brightBlue: "#87afd7",
//   brightPurple: "#afafd7",
//   brightCyan: "#87d7d7",
//   brightWhite: "#dadada",
//   background: "#1c1c1c",
//   foreground: "#d0d0d0",
//   selectionBackground: "#005f5f",
//   cursorColor: "#eeeeee",
// };
// export const colorScheme = {
//   name: "Hacktober",
//   black: "#191918",
//   red: "#b34538",
//   green: "#587744",
//   yellow: "#d08949",
//   blue: "#206ec5",
//   purple: "#864651",
//   cyan: "#ac9166",
//   white: "#f1eee7",
//   brightBlack: "#2c2b2a",
//   brightRed: "#b33323",
//   brightGreen: "#42824a",
//   brightYellow: "#c75a22",
//   brightBlue: "#5389c5",
//   brightPurple: "#e795a5",
//   brightCyan: "#ebc587",
//   brightWhite: "#ffffff",
//   background: "#141414",
//   foreground: "#c9c9c9",
//   selectionBackground: "#141414",
//   cursorColor: "#c9c9c9",
// };

export const colorScheme = {
  name: "MaterialOcean",
  black: "#546e7a",
  red: "#ff5370",
  green: "#c3e88d",
  yellow: "#ffcb6b",
  blue: "#82aaff",
  purple: "#c792ea",
  cyan: "#89ddff",
  white: "#ffffff",
  brightBlack: "#546e7a",
  brightRed: "#ff5370",
  brightGreen: "#c3e88d",
  brightYellow: "#ffcb6b",
  brightBlue: "#82aaff",
  brightPurple: "#c792ea",
  brightCyan: "#89ddff",
  brightWhite: "#ffffff",
  background: "#0f111a",
  foreground: "#8f93a2",
  selectionBackground: "#1f2233",
  cursorColor: "#ffcc00",
};

// export const colorScheme = {
//   black: "#07080d",
//   red: "#ffc0b9",
//   green: "#b3f6c0",
//   yellow: "#fce094",
//   blue: "#a6dbff",
//   purple: "#ffcaff",
//   cyan: "#8cf8f7",
//   white: "#eef1f8",
//   brightBlack: "#4f5258",
//   brightRed: "#ffc0b9",
//   brightGreen: "#b3f6c0",
//   brightYellow: "#fce094",
//   brightBlue: "#a6dbff",
//   brightPurple: "#ffcaff",
//   brightCyan: "#8cf8f7",
//   brightWhite: "#eef1f8",
//   background: "#14161b",
//   foreground: "#e0e2ea",
//   selectionBackground: "#4f5258",
//   cursorColor: "#9b9ea4",
// };

// export const colorScheme = {
//   name: "Adventure",
//   black: "#040404",
//   red: "#d84a33",
//   green: "#5da602",
//   yellow: "#eebb6e",
//   blue: "#417ab3",
//   purple: "#e5c499",
//   cyan: "#bdcfe5",
//   white: "#dbded8",
//   brightBlack: "#685656",
//   brightRed: "#d76b42",
//   brightGreen: "#99b52c",
//   brightYellow: "#ffb670",
//   brightBlue: "#97d7ef",
//   brightPurple: "#aa7900",
//   brightCyan: "#bdcfe5",
//   brightWhite: "#e4d5c7",
//   background: "#040404",
//   foreground: "#feffff",
//   selectionBackground: "#606060",
//   cursorColor: "#feffff",
// };

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        ...colorScheme,
      },
    },
  },
  plugins: [],
};
export default config;
